=== Mac0z/XMediaStream/shoutcast_client.dtd
<!ELEMENT shoutcast_client (mysql, general, txn_handler)>
<!ELEMENT mysql (hostname, username, password, database, port)>
<!ELEMENT hostname (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT database (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT general (batch_time, batch_size, source_name, genres)>
<!ELEMENT batch_time (#PCDATA)>
<!ELEMENT batch_size (#PCDATA)>
<!ELEMENT source_name (#PCDATA)>
<!ELEMENT genres (#PCDATA)>
<!ELEMENT txn_handler ( hostname, port)>
<!ELEMENT logging (enabled_levels)>
<!ELEMENT enabled_levels (#PCDATA)>

=== Mac0z/XMediaStream/christmas_client.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE shoutcast_client SYSTEM "shoutcast_client.dtd">
<shoutcast_client>
    <mysql>
        <hostname>localhost</hostname>
        <username>xms</username>
        <password>xms</password>
        <database>XMediaStream_dev</database>
        <port>3306</port>
    </mysql>
    
    <general>
        <batch_time>100</batch_time>
        <batch_size>32768</batch_size>
        <source_name>christmas</source_name>
        <genres>Holiday</genres>
    </general>
    
    <txn_handler>
        <hostname>localhost</hostname>
        <port>7000</port>
    </txn_handler>

    <multicast>
        <address>224.0.1.1</address>
        <port>1234</port>
        <ttl>0</ttl>
    </multicast>

    <logging>
        <enabled_levels>INFO WARNING ERROR</enabled_levels>
    </logging>
    
</shoutcast_client>
